core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    # path('api-v1',include('api.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp.views import *

app_name = "main"
urlpatterns = [

    path('',login_user, name='login' ),
    path('logout/',logout_user, name='logout' ),

    path('Asosiy',index, name='index' ),
    path("Qurilmalar/",qurilma, name='qurilma' ),
    path("Ro'yxatlar/",table, name='table' ),
    path("Statistika/",statistika, name='statistika' ),
    
    path("Xodimlar/",users, name='users' ),
    path('user/update/<int:pk>/', update_user, name='update_user'),
    path('user/delate/<int:pk>/', delete_user, name='delete_user'),
    
    
    path("Malumotlar/",setting, name='setting' ),
    path("Malumotlar/Viloyat-kiritish",add_region, name='add_region' ),
    path("Malumotlar/Tuman-kiritish",add_district, name='add_district' ),
    path("Malumotlar/qurilma-turi",add_device_type, name='add_device_type' ),

    path('qurilma/update/<int:pk>/', update_qurilma, name='update_qurilma'),
    path('qurilma/delete/<int:pk>/', delete_table, name='delete_table'),
    
    
    path('district/update/<int:pk>/', update_district, name='update_district'),
    path('district/delete/<int:pk>/', delete_district, name='delete_district'),

    path('Device/update/<int:pk>/', update_device, name='update_device'),
    path('Device/delete/<int:pk>/', delete_device, name='delete_device'),

    path('Region/update/<int:pk>/', update_region, name='update_region'),
    path('Region/delete/<int:pk>/', delete_region, name='delete_region'),
    
    path('qurilma/add-note/', add_userNote, name='add_note'),
    path('qurilma/update-note/<int:pk>/', update_userNote, name='update_note'),
    path('qurilma/delate-note/<int:pk>/', delete_note, name='delete_note'),

    path("topilganlar/", found_device, name='founds' ),
    path('topilganlar/<int:pk>/', found_device_detail, name='found'),
    path('topilganlar/<int:pk>/delete/', delete_found_device, name='delete_found_device'),



]

templates/create/add_device_type.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma Kiritish Bo'limi</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Saqlash</button>
</form>


<h2 class="mt-5">Tizimga Qo'shilgan Malumot</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Qurilma Nomi</th>
            <th>Taxrirlash/O'chirish</th>
        </tr>
    </thead>
    <tbody>
        {% if device %}
            {% for d in device %}
            <tr>
                <td>
                    <h4>{{ d.title }}</h4>
                </td>
                <td>
                    <a href="{% url 'main:update_device' d.pk %}" class="btn btn-outline-success green">Tahrirlash</a>
                    <a href="{% url 'main:delete_device' d.pk %}" class="btn btn-outline-danger red" 
                       onclick="return confirm('Ushbu qurilmani o‘chirishni xohlaysizmi?');">O'chirish</a>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="2" class="text-center">Hozircha hech qanday qurilma qo‘shilmagan.</td>
            </tr>
        {% endif %}
    </tbody>
    
</table>

{% endblock content %}

templates/create/add_district.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma Kiritish Bo'limi</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Saqlash</button>
</form>

<h2 class="mt-5">Tizimga Qo'shilgan Malumot</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Tuman Nomi</th>
            <th>Taxrirlash/O'chirish</th>
        </tr>
    </thead>
    <tbody>
        {% if district %}
        {% for d in district %}
        <tr>
            <td>
                <h4>{{ d.title }}</h4>
            </td>
            <td>
                <a href="{% url 'main:update_district' d.pk %}" class="btn btn-outline-success green">Tahrirlash</a>
                <a href="{% url 'main:delete_district' d.pk %}" class="btn btn-outline-danger red" 
                onclick="return confirm('Ushbu qurilmani o‘chirishni xohlaysizmi?');">O'chirish</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="2" class="text-center">Hozircha hech qanday qurilma qo‘shilmagan.</td>
        </tr>
        {% endif %}
    </tbody>
</table>



{% endblock content %}

templates/create/add_note.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>
         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

    <h2>Foydalanuvchi Eslatma Qo'shish</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-primary mt-3 search-btn">Saqlash</button>
        <a href="{% url 'main:index' %}" class="btn btn-outline-secondary greey mt-3">Bekor qilish</a>
    </form>
    <div class="row">
        {% for note in userNote %}
        <div class="col col-sm-12 col-md-12 col-lg-6 col-xl-4 cards m-2">
            <img src="{{ note.photo.url }}" width='400' alt="Tasodifiy Rasm">
            <h4>{{ note.title }}</h4>
            <p>{{ note.body }}</p>
            <div class="d-flex justify-content-evenly">
                <a href="{% url 'main:update_note' note.pk %}" class="btn btn-outline-success green mt-2">Taxrirlash</a>
                <a href="{% url 'main:delete_note' note.pk %}" class="btn btn-outline-danger red mt-2">O'chirish</a>
            </div>
        </div>
        {% endfor %}
 
    </div>



{% endblock content %}

templates/create/add_region.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>
         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma Kiritish Bo'limi</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Saqlash</button>
</form>

<h2 class="mt-5">Tizimga Qo'shilgan Malumot</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Viloyat Nomi</th>
            <th>Taxrirlash/O'chirish</th>
        </tr>
    </thead>
    <tbody>
        {% if region %}
        {% for d in region %}
        <tr>
            <td>
                <h4>{{ d.title }}</h4>
            </td>
            <td>
                <a href="{% url 'main:update_region' d.pk %}" class="btn btn-outline-success green">Tahrirlash</a>
                <a href="{% url 'main:delete_region' d.pk %}" class="btn btn-outline-danger red" 
                onclick="return confirm('Ushbu qurilmani o‘chirishni xohlaysizmi?');">O'chirish</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="2" class="text-center">Hozircha hech qanday qurilma qo‘shilmagan.</td>
        </tr>
        {% endif %}
    </tbody>
</table>



{% endblock content %}

templates/create/base.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma Kiritish Bo'limi</h2>
<div class="d-flex flex-wrap justify-content-evenly">
    
    <div class="card" style="width: 22rem;">
        <div class="card-body">
          <h5 class="card-title">Viloyat kiritish</h5>
          <p class="card-text">Tizim foydalanuvchilar uchun malumot kiritish</p>
          <a href="{% url 'main:add_region' %}" class="btn btn-outline-primary blue">Kiritish</a>
        </div>
    </div>
    
    <div class="card" style="width: 22rem;">
        <div class="card-body">
          <h5 class="card-title">Tuman kiritish</h5>
          <p class="card-text">Tizim foydalanuvchilar uchun malumot kiritish</p>
          <a href="{% url 'main:add_district' %}" class="btn btn-outline-primary blue">Kiritish</a>
        </div>
    </div>
    
    <div class="card" style="width: 22rem;">
        <div class="card-body">
          <h5 class="card-title">Qurilma kiritish</h5>
          <p class="card-text">Tizim foydalanuvchilar uchun malumot kiritish</p>
          <a href="{% url 'main:add_device_type' %}" class="btn btn-outline-primary blue">Kiritish</a>
        </div>
    </div>

    <div class="card" style="width: 22rem;">
        <div class="card-body">
          <h5 class="card-title">foydalanuvchilar uchun</h5>
          <p class="card-text">Tizimda Asosiy sahifaga malumot kiritish</p>
          <a href="{% url 'main:add_note' %}" class="btn btn-outline-primary blue">Kiritish</a>
        </div>
    </div>
    

    
</div>




{% endblock content %}

templates/create/update_device.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma turini tahrirlash</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Saqlash</button>
    <a href="{% url 'main:add_device_type' %}" class="btn btn-outline-secondary greey">Bekor qilish</a>
</form>



{% endblock content %}

templates/create/update_district.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma Kiritish Bo'limi</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Yangilash</button>
    <a href="{% url 'main:add_district' %}" class="btn btn-outline-secondary greey">Bekor qilish</a>
</form>


{% endblock content %}

templates/create/update_note.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>
         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}


    <h2>Foydalanuvchi Eslatmani Tahrirlash</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success mt-3 green">Yangilash</button>
        <a href="{% url 'main:index' %}" class="btn btn-outline-secondary greey mt-3">Bekor qilish</a>
    </form>


{% endblock content %}

templates/create/update_region.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Qurilma kiritish</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Viloyat Nomini tahrirlash</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Saqlash</button>
    <a href="{% url 'main:add_region' %}" class="btn btn-outline-secondary greey">Bekor qilish</a>
</form>



{% endblock content %}

templates/create/update_user.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:setting' %}">Xodimlar</a>

             
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2 class="mt-5">Foydalanuvchini Tahrirlash</h2>

<!-- Xabarlarni ko'rsatish -->
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} mt-2" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}


<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary search-btn">Saqlash</button>
    <a href="{% url 'main:users' %}" class="btn btn-outline-secondary greey">Bekor qilish</a>
</form>



{% endblock content %}