core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    # path('api-v1',include('api.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp.views import *

app_name = "main"
urlpatterns = [

    path('',login_user, name='login' ),
    path('logout/',logout_user, name='logout' ),

    path('Asosiy',index, name='index' ),
    path("Qurilmalar/",qurilma, name='qurilma' ),
    path("Ro'yxatlar/",table, name='table' ),
    path("Statistika/",statistika, name='statistika' ),
    
    path("Xodimlar/",users, name='users' ),
    path('user/update/<int:pk>/', update_user, name='update_user'),
    path('user/delate/<int:pk>/', delete_user, name='delete_user'),
    
    
    path("Malumotlar/",setting, name='setting' ),
    path("Malumotlar/Viloyat-kiritish",add_region, name='add_region' ),
    path("Malumotlar/Tuman-kiritish",add_district, name='add_district' ),
    path("Malumotlar/qurilma-turi",add_device_type, name='add_device_type' ),

    path('qurilma/update/<int:pk>/', update_qurilma, name='update_qurilma'),
    path('qurilma/delete/<int:pk>/', delete_table, name='delete_table'),
    
    
    path('district/update/<int:pk>/', update_district, name='update_district'),
    path('district/delete/<int:pk>/', delete_district, name='delete_district'),

    path('Device/update/<int:pk>/', update_device, name='update_device'),
    path('Device/delete/<int:pk>/', delete_device, name='delete_device'),

    path('Region/update/<int:pk>/', update_region, name='update_region'),
    path('Region/delete/<int:pk>/', delete_region, name='delete_region'),
    
    path('qurilma/add-note/', add_userNote, name='add_note'),
    path('qurilma/update-note/<int:pk>/', update_userNote, name='update_note'),
    path('qurilma/delate-note/<int:pk>/', delete_note, name='delete_note'),

    path("topilganlar/", found_device, name='founds' ),
    path('topilganlar/<int:pk>/', found_device_detail, name='found'),
    path('topilganlar/<int:pk>/delete/', delete_found_device, name='delete_found_device'),



]

templates/__navbar-left.html
{% load static %}

<nav class="navbar-left">  
    <div class="clock">
        <p class="date">{{ times|date:"d-m-Y"}}</p>
        <p class="time" id="time">{{ times|date:"H:i:s" }}</p>
        <img class="close" src="{% static 'img/close.png' %}" alt="">

    </div>
    <ul class="navbar-left-ul-1">
        <li><a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"><span>|</span><p>Asosiy</p></a></li>
        <li><a href="{% url 'main:qurilma' %}"><img src="{% static 'img/tablet.svg' %}" alt="home"><span>|</span><p>Qurilmalar</p></a></li>
        <li><a href="{% url 'main:table' %}"><img src="{% static 'img/table.svg' %}" alt="home"><span>|</span><p>Ro'yxatlar</p></a></li>
        <li><a href="{% url 'main:statistika' %}"><img src="{% static 'img/diagram.svg' %}" alt="home"><span>|</span><p>Statistika</p></a></li>
        {% if request.user.is_superuser %}
        <li><a href="{% url 'main:founds' %}"><img src="{% static 'img/check.svg' %}" alt="chack"><span>|</span><p>Topilganlar</p></a></li>
        <li><a href="{% url 'main:users' %}"><img src="{% static 'img/user.svg' %}" alt="home"><span>|</span><p>Xodimlar</p></a></li>
        <li><a href="{% url 'main:setting' %}"><img src="{% static 'img/laptop.svg' %}" alt="home"><span>|</span><p>Qurilma kiritish</p></a></li>
        
        {% endif %}
    </ul>
    <ul class="logout-ul">
        <li><a href="{% url 'main:logout' %}"><img src="{% static 'img/logout.svg' %}" alt="home"><span>|</span><p>Chiqish</p></a></li>
    </ul>
</nav>

templates/found-detail.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
        <div class="toogle">
            <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:index' %}">Asosiy</a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:table' %}">Xodimlar</a>

        </div>

        <div class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </div>
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<h2>Qurilma Batafsil</h2>
<div class="container mt-5">
    <table class="table table-bordered">
        <tr>
            <th>IMEI</th>
            <td>{{ device.imei.imei }}</td>
        </tr>
        <tr>
            <th>Boshlanish sanasi</th>
            <td>{{ device.active_started }}</td>
        </tr>
        <tr>
            <th>Tugash sanasi</th>
            <td>{{ device.active_finished }}</td>
        </tr>
        <tr>
            <th>Operator</th>
            <td>{{ device.operator }}</td>
        </tr>
        <tr>
            <th>Telefon raqami</th>
            <td>{{ device.phone_number }}</td>
        </tr>
        <tr>
            <th>Ko'rilganmi?</th>
            <td>{{ device.is_viewed|yesno:"Ha,Yo'q" }}</td>
        </tr>
    </table>
    <a href="{% url 'main:founds' %}" class="btn btn-primary blue">Orqaga</a>
    
</div>
{% endblock content %}
{% block js %}
document.addEventListener('DOMContentLoaded', function () {
const modalElement = document.getElementById('exampleModal');
const bootstrapModal = new bootstrap.Modal(modalElement);

if (
modalElement &&
(modalElement.querySelector('.alert') || modalElement.querySelector('.text-danger'))
) {
bootstrapModal.show();
}

const formElement = document.getElementById('id_form');

if (formElement) {
modalElement.addEventListener('hidden.bs.modal', function () {

var loc = window.location;
window.location = loc.protocol + '//' + loc.host + loc.pathname + loc.search;
});
}
});
{% endblock js %}

templates/found.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
        <div class="toogle">
            <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:index' %}">Asosiy</a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:table' %}">Xodimlar</a>

        </div>

        <div class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </div>
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<div class="modal {% if not messages %}fade{% endif %}" id="exampleModal" tabindex="-1"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content bg-custom-dark text-light">
            <form method="post" id="id_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Fayl yulash</h5>
                </div>
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <div class="custom-file   border border-white">
                            <input type="file" class="custom-file-input" id="inputGroupFile01" name="uploaded_file" required>
                            <label class="custom-file-label" for="inputGroupFile01">Fayl tanlash</label>
                        </div>
                    </div>
                    {% if file_error %}
                    <div class="alert">{{ file_error }}</div>
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" data-bs-dismiss="modal">Bekor qilish</button>
                    <button type="submit">Yuborish</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="ms-auto">
        <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-outline-success green">Fayl yuklash</a>
        <a href="?export=true" class="btn btn-outline-primary search-btn">Excelga yuklash</a>
    </div>
</div>


<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>IMEI</th>
            <th>Operator</th>
            <th>Telefon raqami</th>
            <th>Boshlanish sanasi</th>
            <th>Tugash sanasi</th>
            {% comment %} <th>O'chirish</th> {% endcomment %}
        </tr>
    </thead>
    <tbody>
        {% for device in found_devices %}
        <tr class="{% if device.is_viewed %} text-secondary {% endif %}">
            <td>{{ forloop.counter }}</td>                
            <td><a href="{% url 'main:found' device.pk %}" class="device-pk">{{ device.imei.imei }}</a></td>
            <td>{{ device.operator }}</td>
            <td>{{ device.phone_number }}</td>
            <td>{{ device.active_started }}</td>
            <td>{{ device.active_finished }}</td>
            {% comment %} <td>
                <a href="{% url 'main:delete_found_device' device.pk %}" class="btn btn-outline-danger red" onclick="return confirm('Ushbu qurilmani malumotini o‘chirishni xohlaysizmi?');">Delete</a>
            </td> {% endcomment %}
        </tr>
        {% empty %}
        <tr>
            <td colspan="6" class="text-center">Ma'lumot topilmadi</td>
        </tr>
        {% endfor %}
    </tbody>
    
</table>




{% endblock content %}
{% block js %}
document.addEventListener('DOMContentLoaded', function () {
const modalElement = document.getElementById('exampleModal');
const bootstrapModal = new bootstrap.Modal(modalElement);

if (
modalElement &&
(modalElement.querySelector('.alert') || modalElement.querySelector('.text-danger'))
) {
bootstrapModal.show();
}

const formElement = document.getElementById('id_form');

if (formElement) {
modalElement.addEventListener('hidden.bs.modal', function () {

var loc = window.location;
window.location = loc.protocol + '//' + loc.host + loc.pathname + loc.search;
});
}
});
{% endblock js %}

templates/index.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">

             
         </div>
         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}
    
    <h2>Foydalanuvchilar uchun elatma </h2>
    <div class="row">
        {% for note in userNote %}
        <div class="col col-sm-12 col-md-12 col-lg-6 col-xl-4 cards ">
            <img src="{{ note.photo.url }}" width='400' alt="Tasodifiy Rasm">
            <h4>{{ note.title }}</h4>
            <p>{{ note.body }}</p>
            
            {% if note.links %}
            <a href="{{ note.links }}">Ulanish</a>
            {% endif %}
            
        </div>
        {% endfor %}
 
    </div>

{% endblock content %}

templates/table.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
        <div class="toogle">
            <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:index' %}">Asosiy</a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:table' %}">Ro'yxatlar</a>
        </div>

        {% if request.user.is_superuser %}
        <a href="{% url 'main:users' %}" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
        {% else %}
        <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
        {% endif %}
    </div>
</nav>
{% endblock navbar-top %}

{% block content %}
<section class="article">
    <div class="form-container">
        <!-- Search Form -->
        <form class="d-flex" role="search" method='get'>
            <input class="form-control search-input" type="search" placeholder="Qurilmani qidiring" value="{{ request.GET.search }}" aria-label="Search">
            <button class="btn btn-outline-primary search-btn" type="submit">Search</button>
        </form>

        <!-- Device List Table -->
        <table class="table table-hover mt-4">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Ism</th>
                    <th>Tuman</th>
                    <th>Qurilma</th>
                    <th>Qurilma Nomi</th>
                    <th>IMEI</th>
                    <th>Yo‘qolgan Vaqti</th>
                    <th>Tell Raqami</th>
                    <th>Ariza Fayli</th>
                    <th>O'chirish</th>
                </tr>
            </thead>
            <tbody>
                {% for devise in user_devices %}
                <tr>
                    <td>{{ devise.id }}</td>
                    {% if user.is_superuser %}
                    <td><a href="{% url 'main:update_qurilma' devise.id %}" class="link-a">{{ devise.name }}</a></td>
                    {% else %}
                    <td><a href="#" class="link-a">{{ devise.name }}</a></td>
                    {% endif %}
                    <td>{{ devise.categoryDistrict }}</td>
                    <td>{{ devise.device_type }}</td>
                    <td>{{ devise.device_name }}</td>
                    <td>{{ devise.get_imeis }}</td>
                    <td>{{ devise.data|date:"d-m-Y H:i" }}</td>
                    <td>{{ devise.phone_number }}</td>     
                    <td>
                        {% if devise.file %}
                        <a href="{{ devise.file.url }}" class="link-b" target="_blank">Fayl</a>
                        {% else %}
                        <span>Fayl mavjud emas</span>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'main:delete_table' devise.id %}" class="btn red btn-outline-danger" onclick="return confirm('Haqiqatan ham o‘chirmoqchimisiz?')">O'chirish</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="10" class="text-center">Hech qanday ma'lumot topilmadi.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Excel Export Button -->
        {% if user.is_superuser %}
        <div class="btn-box">
            <a href="?export_excel=true" class="btn1">Excelga yuklash</a>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

templates/update_qurilma.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
         <div class="toogle">
             <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:index' %}">Asosiy</a>
             <img src="{% static 'img/line.png' %}" alt="line">
             <a href="{% url 'main:qurilma' %}">Qurilmalar</a>
         </div>

         {% if request.user.is_superuser %}
         <a href="{% url 'main:users' %}" class="box-user">
             <img src="{% static 'img/user.svg' %}" alt="user">
             <span>|</span>
             <p>{{ user.full_name }}</p>
         </a>
         {% else %}
         <a href="#" class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </a>
         {% endif %}
    </div>
</nav>
{% endblock navbar-top %}

{% block content %}
<section class="article">
    <div class="form-container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="{{ form.name.id_for_label }}" class="form-label">Foydalanuvchi Ismi</label>
                {{ form.name }}
            </div>
        
            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <img class="arrow" src="{% static 'img/arrow-right.png' %}">
                    <label for="{{ form.categoryRegion.id_for_label }}">Viloyat</label>
                    {{ form.categoryRegion }}
                </div>
                <div class="col-md-6">
                    <img class="arrow" src="{% static 'img/arrow-right.png' %}">
                    <label for="{{ form.categoryDistrict.id_for_label }}">Tuman</label>
                    {{ form.categoryDistrict }}
                </div>
            </div>
        
            <div class="mb-3">
                <label for="{{ form.device_type.id_for_label }}">Qurilma Turi</label>
                {{ form.device_type }}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.device_name.id_for_label }}">Qurilma Nomi</label>
                {{ form.device_name }}
            </div>

            <div class="row g-3">
                <div class="mb-3 col-md-6">
                    <label for="{{ form.data.id_for_label }}">Yo‘qolgan Vaqti</label>
                    {{ form.data }}
                </div>
            
                <div class="mb-3 col-md-6">
                    <label for="{{ form.phone_number.id_for_label }}">Telefon Raqami</label>
                    {{ form.phone_number }}
                </div>
            </div>    

            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    {{ form.imei_formset.management_form }}
                    <table class="mb-3" id="imei_table">
                        {% for form in form.imei_formset %}
                            <tr class="imei-row mb-3">
                                <td>{{ form.imei }}</td>
                                <td><a href="#" class="delete-form btn btn-danger">&times;</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="col-md-6">
                    <button type="button" id="add_imei" class="btn mb-3">IMEI qo'shish</button>
                </div>
            </div>

            <div class="col-md-12">
                <label for="{{ form.file.id_for_label }}">Ariza Fayli</label>
                {{ form.file }}
            </div>

            <div class="form-check">
                <button type="submit"><img src="{% static 'img/check.svg' %}" alt="chack"><span>|</span>
                    Yuborish
                </button>
            </div>
            <a href="{% url 'main:table' %}" class="closes">Bekor qilish</a>
        </form>
    </div>
</section>
{% endblock content %}

{% block js %}
    document.addEventListener('DOMContentLoaded', function () {
        console.log("JavaScript yuklandi!");

        // Viloyatni o'zgartirganda tumanlarni yangilash
        const regionSelect = document.getElementById('id_categoryRegion');
        const districtSelect = document.getElementById('districtSelect');

        if (regionSelect) {
            console.log("Viloyat select elementi mavjud.");
            regionSelect.addEventListener('change', function () {
                const regionId = this.value; // Viloyatning ID-si

                // Tumanlarni tozalash
                districtSelect.innerHTML = '<option value="">Tuman tanlang</option>';

                if (regionId) {
                    console.log("Viloyat tanlandi, AJAX so'rov yuboriladi");
                    // AJAX so'rov yuborish
                    fetch(`/get_districts/${regionId}/`)
                        .then(response => response.json())
                        .then(data => {
                            data.districts.forEach(district => {
                                const option = document.createElement('option');
                                option.value = district.id;
                                option.textContent = district.title;
                                districtSelect.appendChild(option); // Yangi tumanlarni qo'shish
                            });
                        })
                        .catch(error => console.error('Tumanlarni yuklashda xatolik:', error));
                }
            });
        }

        // IMEI form qo'shish
        const addImeiButton = document.getElementById('add_imei');
        const formsetTable = document.getElementById('imei_table');
        const totalForms = document.getElementById('id_imeis-TOTAL_FORMS');

        if (addImeiButton) {
            console.log("IMEI qo'shish tugmasi mavjud.");
            addImeiButton.addEventListener('click', function () {
                const formCount = parseInt(totalForms.value); // Joriy formalar soni
                console.log(`Joriy formalar soni: ${formCount}`);

                // Yangi qator yaratish
                const newRow = document.createElement('tr');
                newRow.className = 'imei-row mb-2';

                // IMEI input maydoni
                const imeiCell = document.createElement('td');
                const imeiInput = document.createElement('input');
                imeiInput.type = 'text';
                imeiInput.name = `imei_form-${formCount}-imei`;
                imeiInput.className = 'form-control';
                imeiInput.required = true;
                imeiCell.appendChild(imeiInput);

                // O'chirish tugmasi
                const deleteCell = document.createElement('td');
                const deleteButton = document.createElement('a');
                deleteButton.href = '#';
                deleteButton.className = 'delete-form btn btn-danger';
                deleteButton.innerHTML = '&times;';
                deleteCell.appendChild(deleteButton);

                // Yangi qatorni jadvalga qo'shish
                newRow.appendChild(imeiCell);
                newRow.appendChild(deleteCell);
                formsetTable.appendChild(newRow);

                // Formlar sonini yangilash
                totalForms.value = formCount + 1;
            });
        }

        // IMEI form o'chirish
        document.addEventListener('click', function (e) {
            if (e.target.closest('.delete-form')) {
                e.preventDefault();

                const row = e.target.closest('.imei-row'); // Qatorni aniqlash
                if (row) {
                    row.remove(); // Qatorni o'chirish

                    // Formlar sonini yangilash
                    totalForms.value = parseInt(totalForms.value, 10) - 1;
                }
            }
        });
    });
{% endblock js %}

templates/users.html
{% extends "__base.html" %}
{% load static %}
{% block navbar-top %}
<nav class="navbar-top">
    <img src="{% static 'img/menu-bar.png' %}" class="menu" alt="menu">
    <div class="nav-center">
        <div class="toogle">
            <a href="{% url 'main:index' %}"><img src="{% static 'img/home.svg' %}" alt="home"></a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:index' %}">Asosiy</a>
            <img src="{% static 'img/line.png' %}" alt="line">
            <a href="{% url 'main:table' %}">Xodimlar</a>

        </div>

        <div class="box-user">
            <img src="{% static 'img/user.svg' %}" alt="user">
            <span>|</span>
            <p>{{ user.full_name }}</p>
        </div>
    </div>
</nav>
{% endblock navbar-top %}
{% block content %}

<div class="modal {% if not messages %}fade{% endif %}" id="exampleModal" tabindex="-1"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content bg-custom-dark text-light">
            <form method="post" id="id_form">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Xodim qo'shish</h5>
                </div>
                <div class="modal-body">
                    <div class="row mb-3">
                        <div class="col">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">Ismi</label>
                            {{ form.first_name }}
                            {% if form.first_name.errors %}
                            <div class="text-danger small">
                                {{ form.first_name.errors|striptags }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="col">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Familyasi</label>
                            {{ form.last_name }}
                            {% if form.last_name.errors %}
                            <div class="text-danger small">
                                {{ form.last_name.errors|striptags }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <label for="{{ form.phone_number.id_for_label }}" class="form-label">Telefon raqami</label>
                            {{ form.phone_number }}
                            {% if form.phone_number.errors %}
                            <div class="text-danger small">
                                {{ form.phone_number.errors|striptags }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <label for="{{ form.lavel.id_for_label }}" class="form-label">Lavozimi</label>
                            {{ form.lavel }}
                            {% if form.lavel.errors %}
                            <div class="text-danger small">
                                {{ form.lavel.errors|striptags }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Foydalanuvchi nomi</label>
                            {{ form.username }}
                            {% if form.username.errors %}
                            <div class="text-danger small">
                                {{ form.username.errors|striptags }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="col">
                            <label for="{{ form.password.id_for_label }}" class="form-label">Paroli</label>
                            {{ form.password }}
                            {% if form.password.errors %}
                            <div class="text-danger small">
                                {{ form.password.errors|striptags }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-bs-dismiss="modal" >Bekor qilish</button>
                    <button type="submit">Saqlash</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="ms-auto">

        <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
            + | Xodim qo'shish
        </button>
    </div>
</div>

<h2 class="mt-5">Foydalanuvchilar Ro'yxati</h2>


<form class="d-flex" role="search" method='get'>
    <input class="form-control search-input"  placeholder="Foydalanuvchini qidiring" type="search" value="{{ request.GET.search }}" aria-label="Search">
    <button class="btn btn-outline-primary search-btn" type="submit">Search</button>
</form>

<!-- Foydalanuvchilar jadvali -->
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Ism</th>
            <th>Foydalanuvchi</th>
            <th>Lavozimi</th>
            <th>Telefon</th>
            <th>Taxrirlash/O'chirish</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ user.full_name }}</td>
            <td>
                {% if user.is_superuser %}
                    Admin
                {% else %}
                    Foydalanuvchi
                {% endif %}
            </td>
            <td>{{ user.lavel }}</td>
            <td>{{ user.phone_number }}</td>
            <td>
                <a href="{% url 'main:update_user' user.pk %}" class="btn btn-outline-success green">Tahrirlash</a>
                <a href="{% url 'main:delete_user' user.pk %}" class="btn btn-outline-danger red" 
                onclick="return confirm('Ushbu Foydalanuvchini o‘chirishni xohlaysizmi?');">O'chirish</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5" class="text-center">Foydalanuvchilar mavjud emas.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>





{% endblock content %}
{% block js %}
document.addEventListener('DOMContentLoaded', function () {
    const modalElement = document.getElementById('exampleModal');
    const bootstrapModal = new bootstrap.Modal(modalElement);

    if (
      modalElement &&
      (modalElement.querySelector('.alert') || modalElement.querySelector('.text-danger'))
    ) {
      bootstrapModal.show();  
    }

    const formElement = document.getElementById('id_form');

    if (formElement) {
      modalElement.addEventListener('hidden.bs.modal', function () {
        
        var loc = window.location;
        window.location = loc.protocol + '//' + loc.host + loc.pathname + loc.search;
      });
    }
  });
{% endblock js %}